### ISSUE TITLE
Multiple Comparisons Corrections

### ISSUE THREAD

**Issue by Feugs** [DDTBOX/DDTBOX#4]
We could implement the following corrections for multiple comparisons in the toolbox:
- Bonferroni
- Bonferroni-Holm method 
- False Discovery Rate correction (Benjamini-Hochberg procedure)
- Cluster-based correction based on permutation testing or bootstrapping

**Cluster-based correction method**
For an introduction to the rationale behind cluster-based corrections see Maris & Oostenveld (2007) doi:10.1016/j.jneumeth.2007.03.024

For the cluster-based corrections I am thinking of implementing the approach below, and then using simulations to check if it controls the Type 1 error rate correctly. Please let me know if you have suggestions for improvements.
1. Using the classifier performance data run t tests at each step and identify steps at which the classifier performance statistically significantly differs from zero. 
2. Clusters are defined as groups of adjacent steps that are statistically significant. For example, three consecutive steps that are statistically significant are defined as one cluster. Calculate the sum of the test statistics (e.g. absolute t values) for each cluster separately. This is known as the cluster mass.
3. Using the permutation test data (mean permutation test classifier accuracy for each participant) generate a bootstrap sample for each step. Find the steps which are significantly different from zero and calculate the cluster mass for each cluster. Record the test statistic value of the largest cluster mass.
4. Repeat step 3 B times (B = number of bootstrap samples) to generate a distribution of the maximum cluster mass statistic under the null hypothesis. 
5. Check which clusters derived from step 1 have cluster masses above the 95th percentile of the null hypothesis distribution (when using an alpha level of 0.05). These clusters are defined as statistically significant effects. Clusters that do not have a mass larger than the 95th percentile are not declared as statistically significant.

We can test the type 1 error rate using simulations in a similar way to Pernet et al. (2015)        doi:10.1016/j.jneumeth.2014.08.003 . We could also include these simulations in the publication.

**Comment by palday** [comment]
Another place to look for inspiration on these things is the Mass Univariate stuff ([Groppe et al 2011, Psychophysiology](dx.doi.org/10.1111/j.1469-8986.2011.01273.x)).  Although it initially seems to have little in common with our work, _Mass_ univariate suffers from the same multiple testing and computational issues as MVPA -- you could almost view some types of MU as MVPA applied to a single sensor. If I recall correctly, Groppe had implemented his ideas in a similar way to our current MVPA setup -- in many ways dependent on EEGLAB but not a proper plugin, so we may be able to borrow adapt some of his code for our purposes. His software provides the following multiple-comparisons corrections (copied nearly directly from the abstract for the second paper in the two-part series): 
-  permutation-based control of the family-wise error rate (FWER)
- weak control of FWER via cluster-based permutation tests
- permutation-based control of the generalized FWER
- three false discovery rate control procedures)

**Comment by Feugs** [comment]
These look great - I was familiar with Maris & Oostendveld's mass univariate MC correction article but these extra options are nice. Let's add those to the list of options for multiple comparisons corrections.

**Comment by Feugs** [comment]
The following multiple comparisons corrections have been implemented in the toolbox (although they still need extensive debugging and simulation testing). I have included plenty of options to be flexible to different data types and analysis goals:
- Bonferroni
- Holm-Bonferroni
- Strong FWER control based on permutation testing
- Cluster-based weak FWER control based on permutation testing
- Generalised FWER control based on permutation testing
- Benjamini-Hochberg procedure
- Benjamini-Krieger-Yekutieli procedure
- Benjamini-Yekutieli procedure

I have needed to modify the permutation-based procedures as they rely on randomly-assigning condition labels at the group level. As DDTBOX performs permutation tests at the individual level, it does not make sense to then also perform label-switching at the group level. Instead I have relied on bootstrapping the within-subject permutation test decoding accuracies to create the null distributions required in each procedure. 

I will run simulations to assess how the bootstrap-based procedures perform. If anyone has theoretical or practical reasons why this is a bad approach, then speak soon or forever hold your p-values.

**Comment by palday** [comment]
I feel like we might need some synthetic data with a known ground truth to get ideal estimates of some of these values, but I don't know off the top of my head how to create such data. 

Also, on the group vs. individual level -- what do the other MVPA toolboxes ([PyMVPA](http://www.pymvpa.org/),  the [examples](http://martinos.org/mne/stable/auto_examples/index.html#id120) in MNE with Python) do? Performing stats at the individual level and aggregating vs. aggregating and then performing stats at the group level answer two slightly different inferential questions.

Or should we provide support for both? In terms of the plugin, that might make things a bit more complicated, but I think it shouldn't be too much more effort at the API/function level. Thoughts?

**Comment by Feugs** [comment]
I was originally hoping to implement MC corrections at the group level only (running simulations by substituting decoding accuracies with Gaussian noise + a real effect constant), but having synthetic data at the individual level with a ground truth would indeed be very useful. Perhaps a multivariate Gaussian (i.e. noise) compared to a multivariate Gaussian with an added constant vector (noise + 'real' effect vector), or would this be too simple?

I will check PyMVPA and MNE, thanks for directing me to them! I realise that my last comment wasn't quite right - I guess that you could do a group-level permutation test by switching the group-level labels between the "decoding using real labels" and "decoding using permuted labels" conditions. This would test whether the real decoding and permutation test results are exchangeable. I will replace the bootstrap tests with the permuation tests (which I probably should have done in the first place).

Perhaps we could stick to group-level multiple comparisons corrections for the initial release, as these are used to answer the questions that users are most likely to use with the toolbox?

**Comment by danielbrianbennett** [comment]
Group-level multiple comparisons for the initial release sounds very sensible to me.

**Comment by palday** [comment]
Then group-level MC corrections for the initial release it is.
