### ISSUE TITLE
Variable names and scope

### ISSUE THREAD

**Issue by palday** [DDTBOX/DDTBOX#5]
Several of the main variable names (e.g. `STUDY`) clash with variable names that are used by EEGLAB. We should strive to have variable and function names that don't clash with those from EEGLAB, ERPLAB or FieldTrip, as we can reasonably expect our users to be using one or all of those packages. Additionally, we need to reduce the number of and potentially the use of global variables -- this is better programming practice and will help us avoid namespace collisions with the aforementioned EEG packages.

**Comment by Feugs** [comment]
This has now been fixed by removing all global variables and using the structure `cfg` for decoding settings, and `ANALYSIS` for group-level analyses.

(Just closing this old issue)
