### ISSUE TITLE
Z-Score Conversion of Input Data

### ISSUE THREAD

**Issue by Feugs** [DDTBOX/DDTBOX#7]
This feature would convert the data into sets of Z-scores for each step/window before decoding. Converting to Z-scores would allow some isolation of spatial/temporal patterns of activity that are not driven by net amplitude differences between conditions. Using Z-scores we can attempt to remove the net amplitude difference while still being able to decode patterns across sensors or time points.

Z-scores could be calculated for each step (window):
**Across sensors:** Calculate Z-scores across electrodes (for spatial decoding).
**Across time-points:** Calculate Z-scores across time points for each electrode separately (for temporal decoding).

This is probably best done by making a separate function to generate the Z-scored datasets (called before running the DECODING_ERP script). These Z-scored datasets can be saved in a separate folder, and then we can add a varargin input to the main decoding script "DECODING_ERP.m" which can signal to use Z-scored datasets (e.g. in the config file).

I will begin working on this. It should be straightforward to integrate into the updated code (when structures etc. have been renamed).

**Comment by palday** [comment]
How long does the z-transform actually take to compute? If it's a fast transform, then my suggestion would be to **not** store it, but rather compute it during loading, i.e. directly before the MVPA calculations begin. You don't need additional information to compute a Z-transform, but you do need to store extra information to invert it, namely the mean and standard deviation, which admittedly isn't much but still extra bits to keep track of. And given the nature of floating point arithmetic, you don't always get the exact original answer back when you transform and invert.

**Comment by Feugs** [comment]
Currently I have set it to compute Z-scores just before the MVPA calculations begin (in prepare_my_vectors_erp). This seems to be the easiest way for reasons you have mentioned above. 

Also, when you store the Z-scored data before running DDTBOX you also need to change the window width and step width (you need to create extra data points when there are overlapping time points across windows, because observations within a step are z-scored relative to each other). This duplicated data also leads to hard-to-interpret results graphs in the current version.

Here are the durations of the z-scoring process on my machine:
Spatial decoding (128 channels) = 25ms per step.
Temporal decoding (5 time points) = 25ms per step.
Spatio-temporal decoding (5 time points z-scored separately for 128 channels) = 2 seconds per step.

The long running times for spatio-temporal decoding are due to the separate z-scoring operations for each channel. Perhaps we could use the current method (z-scoring the prepared vectors just before SVM classification) and then work on a faster "Z-score and store" option after the initial release?

**Comment by Feugs** [comment]
I've modified the Z-scoring procedure to vectorise instead of run through loops, which has made it much faster.

Here are the **new** durations of the z-scoring process on my machine:
(All for 100 epochs per condition for 2 conditions)
- Spatial decoding (128 channels) = 1ms per step.
- Temporal decoding (5 time points) = 1ms per step.
- Spatio-temporal decoding (5 time points z-scored separately for 128 channels) = 8ms per step.
